# Generated by Django 6.0.4 on 2026-04-17 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players_per_team',
            field=models.IntegerField(default=1, help_text='Number of players required per team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sport_type',
            field=models.CharField(choices=[('badminton', 'Badminton'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball'), ('soccer', 'Soccer'), ('cricket', 'Cricket'), ('table_tennis', 'Table Tennis'), ('other', 'Other')], default='other', help_text='Type of sport for this tournament', max_length=30),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
