# Generated by Django 6.0.4 on 2026-04-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tournament_players_per_team_tournament_sport_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('double_round_robin', 'Double Round Robin'), ('knockout', 'Knockout'), ('double_elimination', 'Double Elimination'), ('consolation', 'Consolation'), ('hybrid', 'Hybrid (Groups + Knockout)')], max_length=30),
        ),
    ]
