# Generated by Django 6.0.4 on 2026-04-19 03:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tournament_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.court'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='expected_teams_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Expected number of teams before the tournament can start'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, help_text='Date from which automatic scheduling should begin', null=True),
        ),
        migrations.CreateModel(
            name='CourtAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.court')),
            ],
            options={
                'ordering': ['court__name', 'weekday', 'start_time'],
            },
        ),
    ]
