# Generated by Django 6.0.4 on 2026-04-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_timeslot_court_tournament_expected_teams_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('setup', 'Setup'), ('registration_open', 'Registration Open'), ('ready', 'Ready for Scheduling'), ('scheduled', 'Schedule Draft Ready'), ('active', 'Active'), ('completed', 'Completed')], default='setup', max_length=20),
        ),
    ]
