# Generated by Django 6.0.4 on 2026-04-19 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tournament_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoShowReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('resolved', 'Resolved'), ('auto_forfeited', 'Auto Forfeited'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('deadline_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absent_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_show_reports_against', to='core.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_show_reports', to='core.match')),
                ('present_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_show_reports_supported', to='core.team')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_show_reports_made', to='core.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
