# Generated by Django 6.0.4 on 2026-04-21 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_teammembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='champion',
            field=models.ForeignKey(blank=True, help_text='Team that won the tournament', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='championships', to='core.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Done'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('forfeited', 'Forfeited'), ('bye', 'Bye')], default='upcoming', max_length=25),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
