# Generated by Django 6.0.4 on 2026-04-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tournament_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='department',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
