# Generated by Django 6.0.4 on 2026-04-23 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_match_dispute_window_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('captain', 'Captain'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='TeamTournamentParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.CharField(blank=True, default='', max_length=5)),
                ('seed', models.IntegerField(default=0)),
                ('availability_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_participations', to='core.tournament')),
            ],
            options={
                'ordering': ['tournament_id', 'seed', 'id'],
                'unique_together': {('team', 'tournament')},
            },
        ),
        migrations.CreateModel(
            name='TeamTournamentCourtPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_preferences', to='core.court')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_preferences', to='core.teamtournamentparticipation')),
            ],
            options={
                'ordering': ['participation_id', 'court_id'],
                'unique_together': {('participation', 'court')},
            },
        ),
    ]
