# Generated by Django 6.0.4 on 2026-05-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_match_dispute_window_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='matches_per_court_per_day',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Maximum matches per court per day for scheduling (0 = no limit, derived from time slots)'),
        ),
    ]
