# Generated by Django 6.0.4 on 2026-04-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_deduplicate_global_teams'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='team',
            name='availability_notes',
        ),
        migrations.RemoveField(
            model_name='team',
            name='group',
        ),
        migrations.RemoveField(
            model_name='team',
            name='preferred_courts',
        ),
        migrations.RemoveField(
            model_name='team',
            name='seed',
        ),
        migrations.RemoveField(
            model_name='team',
            name='status',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='withdrawn_at',
        ),
    ]
