# Generated by Django 6.0.4 on 2026-04-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tournament_registration_mode_team_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, help_text='Expected end date (auto-calculated if left blank)', null=True),
        ),
    ]
