# Generated by Django 5.2.1 on 2026-05-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_match_confirmed_by_alter_match_disputed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtavailability',
            name='matches_per_court_per_day',
            field=models.PositiveIntegerField(default=1, help_text='How many matches should be scheduled on each court for each selected weekday.'),
        ),
    ]
