# Generated by Django 5.2.1 on 2026-05-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_courtavailability_matches_per_court_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtavailability',
            name='additional_start_times',
            field=models.TextField(blank=True, default='', help_text='Comma-separated additional match start times after the first match, e.g. 13:00, 15:30.'),
        ),
    ]
