# Generated by Django 6.0.4 on 2026-05-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_matches_per_court_per_day'),
        ('core', '0021_courtavailability_additional_start_times'),
    ]

    operations = [
    ]
