# Generated by Django 6.0.4 on 2026-05-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_20260503_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtournamentparticipation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Forming)'), ('active', 'Active'), ('withdrawn', 'Withdrawn')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentindividualregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Forming)'), ('active', 'Active'), ('withdrawn', 'Withdrawn')], default='active', max_length=20),
        ),
    ]
