# Generated by Django 6.0.4 on 2026-05-03 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_pending_status_to_team_participation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disbanded', 'Disbanded')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('setup', 'Setup'), ('registration_open', 'Registration Open'), ('ready', 'Ready for Scheduling'), ('scheduled', 'Schedule Draft Ready'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='setup', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('team_invite_received', 'Team invite received'), ('team_invite_accepted', 'Team invite accepted'), ('team_invite_declined', 'Team invite declined'), ('registration_approved', 'Tournament registration approved'), ('registration_rejected', 'Tournament registration rejected'), ('match_result_submitted', 'Match result submitted (action required)'), ('match_result_confirmed', 'Match result confirmed'), ('match_result_disputed', 'Match result disputed'), ('dispute_resolved', 'Dispute resolved'), ('reschedule_requested', 'Reschedule requested'), ('reschedule_accepted', 'Reschedule accepted'), ('reschedule_declined', 'Reschedule declined'), ('tournament_starting_soon', 'Tournament starting soon'), ('bracket_published', 'Tournament bracket published'), ('tournament_cancelled', 'Tournament cancelled'), ('tournament_paused', 'Tournament paused'), ('tournament_resumed', 'Tournament resumed'), ('disqualified', 'Disqualification notice'), ('walkover_awarded', 'Walkover awarded'), ('organizer_announcement', 'Organizer announcement'), ('organizer_application_result', 'Organizer application result')], max_length=50)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invites_received', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('team', 'invited_user')},
            },
        ),
    ]
