# Generated by Django 6.0.4 on 2026-05-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_team_status_alter_tournament_status_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtournamentparticipation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Forming)'), ('active', 'Active'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentindividualregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Forming)'), ('active', 'Active'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn')], default='active', max_length=20),
        ),
    ]
