# Generated by Django 6.0.4 on 2026-05-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_waitlisted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('captain', 'Captain'), ('member', 'Member'), ('sub', 'Substitute')], default='member', max_length=20),
        ),
    ]
