# Generated by Django 6.0.4 on 2026-05-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_sub_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('team_invite_received', 'Team invite received'), ('team_invite_accepted', 'Team invite accepted'), ('team_invite_declined', 'Team invite declined'), ('registration_approved', 'Tournament registration approved'), ('registration_rejected', 'Tournament registration rejected'), ('registration_promoted_from_waitlist', 'Registration promoted from waitlist'), ('match_result_submitted', 'Match result submitted (action required)'), ('match_result_confirmed', 'Match result confirmed'), ('match_result_disputed', 'Match result disputed'), ('dispute_resolved', 'Dispute resolved'), ('reschedule_requested', 'Reschedule requested'), ('reschedule_accepted', 'Reschedule accepted'), ('reschedule_declined', 'Reschedule declined'), ('tournament_starting_soon', 'Tournament starting soon'), ('bracket_published', 'Tournament bracket published'), ('tournament_cancelled', 'Tournament cancelled'), ('tournament_paused', 'Tournament paused'), ('tournament_resumed', 'Tournament resumed'), ('disqualified', 'Disqualification notice'), ('walkover_awarded', 'Walkover awarded'), ('organizer_announcement', 'Organizer announcement'), ('organizer_application_result', 'Organizer application result'), ('general', 'General notification')], max_length=50),
        ),
    ]
