# Generated by Django 5.2.17 on 2026-09-19 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_created_by(apps, schema_editor):
    """Attribute existing tournaments from their 'tournament_created' audit row.

    That log entry is the only record of authorship prior to this field. Rows
    with no attributable entry stay NULL; _can_manage_tournament treats those
    as legacy and lets any verified organizer manage them, so nothing is
    orphaned.
    """
    Tournament = apps.get_model("core", "Tournament")
    AuditLog = apps.get_model("core", "AuditLog")

    for tournament in Tournament.objects.filter(created_by__isnull=True).iterator():
        entry = (
            AuditLog.objects.filter(
                tournament_id=tournament.pk, action="tournament_created"
            )
            .exclude(user__isnull=True)
            .order_by("timestamp")
            .first()
        )
        if entry is not None:
            tournament.created_by_id = entry.user_id
            tournament.save(update_fields=["created_by"])


def unset_created_by(apps, schema_editor):
    """Reverse is a no-op: the column is dropped by the AddField reversal."""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_tournament_enable_third_place_match"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Organizer who created this tournament. Only they (and site administrators) may administer it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tournaments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_created_by, unset_created_by),
    ]
