# Generated by Django 5.2.17 on 2026-09-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_tournament_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="format",
            field=models.CharField(
                choices=[
                    ("round_robin", "Round Robin"),
                    ("double_round_robin", "Double Round Robin"),
                    ("knockout", "Knockout"),
                    (
                        "double_elimination",
                        "Double Elimination (losers bracket not yet implemented)",
                    ),
                    ("consolation", "Consolation"),
                    ("hybrid", "Hybrid (Groups + Knockout)"),
                ],
                max_length=30,
            ),
        ),
    ]
