# Generated by Django 5.2.17 on 2026-09-19 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


LIVE_STATUSES = ("setup", "registration_open", "ready", "scheduled", "active", "paused")


def convert_sub_memberships(apps, schema_editor):
    """Turn role="sub" TeamMemberships into tournament-scoped substitute rows.

    A sub membership carries no tournament, and under the old behaviour it
    applied to every tournament the team competed in. Rather than silently
    revoking access mid-tournament, create a substitute row for each of the
    team's live participations — preserving exactly what the sub could do
    before, but now visible and removable per tournament.
    """
    TeamMembership = apps.get_model("core", "TeamMembership")
    TeamTournamentParticipation = apps.get_model("core", "TeamTournamentParticipation")
    TournamentSubstitute = apps.get_model("core", "TournamentSubstitute")

    for membership in TeamMembership.objects.filter(role="sub").iterator():
        participations = TeamTournamentParticipation.objects.filter(
            team_id=membership.team_id,
            tournament__status__in=LIVE_STATUSES,
        )
        for participation in participations:
            TournamentSubstitute.objects.get_or_create(
                participation_id=participation.pk, user_id=membership.user_id
            )
        membership.delete()


def restore_sub_memberships(apps, schema_editor):
    """Collapse substitute rows back into role="sub" memberships."""
    TeamMembership = apps.get_model("core", "TeamMembership")
    TournamentSubstitute = apps.get_model("core", "TournamentSubstitute")

    for sub in TournamentSubstitute.objects.select_related("participation").iterator():
        TeamMembership.objects.get_or_create(
            team_id=sub.participation.team_id,
            user_id=sub.user_id,
            defaults={"role": "sub"},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_honest_double_elimination_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentSubstitute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substitutes_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutes",
                        to="core.teamtournamentparticipation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitute_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["participation_id", "created_at"],
                "unique_together": {("participation", "user")},
            },
        ),
        migrations.RunPython(convert_sub_memberships, restore_sub_memberships),
    ]
