# Generated by Django 5.2.17 on 2026-09-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_tournament_substitute"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="dispute_window_minutes",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Minutes an opponent has to dispute a submitted score before it auto-locks.",
            ),
        ),
    ]
