# Generated by Django 5.2.17 on 2026-09-20 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_dispute_window_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="next_loser_match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_loser_matches",
                to="core.match",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="next_loser_match_slot",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="next_match_slot",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="enable_bracket_reset",
            field=models.BooleanField(
                default=True,
                help_text="Double elimination only. The losers-bracket champion reaches the grand final with one defeat and the winners-bracket champion with none, so a single grand final would eliminate the former on one loss. With this on, a grand final won by the losers-bracket champion is followed by a decider. Turn it off for a fixed match count at the cost of that asymmetry.",
            ),
        ),
    ]
