# Generated by Django 5.2.17 on 2026-09-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_double_elimination_losers_bracket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="format",
            field=models.CharField(
                choices=[
                    ("round_robin", "Round Robin"),
                    ("double_round_robin", "Double Round Robin"),
                    ("knockout", "Knockout"),
                    ("double_elimination", "Double Elimination"),
                    ("consolation", "Consolation"),
                    ("hybrid", "Hybrid (Groups + Knockout)"),
                ],
                max_length=30,
            ),
        ),
    ]
