# Generated by Django 5.2.17 on 2026-09-24 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_honest_double_elimination_label_restored"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("ask", "Question"), ("recap", "Recap")],
                        default="ask",
                        max_length=10,
                    ),
                ),
                ("question", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("route", models.JSONField(blank=True, null=True)),
                ("facts", models.JSONField(blank=True, null=True)),
                ("answer", models.TextField(blank=True, default="")),
                ("answer_verified", models.BooleanField(default=False)),
                ("error", models.CharField(blank=True, default="", max_length=255)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("timings", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_questions",
                        to="core.tournament",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="aiq_status_created"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="aiq_user_created"
                    ),
                ],
            },
        ),
    ]
