# Generated by Django 5.2.17 on 2026-09-25 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_ai_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquestion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='core.aiquestion'),
        ),
        migrations.AddField(
            model_name='aiquestion',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiquestion',
            name='unchecked_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
