# Generated by Django 5.2.17 on 2026-09-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_ai_question_system_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiquestion',
            name='kind',
            field=models.CharField(choices=[('ask', 'Question'), ('recap', 'Recap'), ('team_news', 'Team news')], default='ask', max_length=10),
        ),
    ]
